# -*- coding: utf-8 -*-
"""print hello in python .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Fp6BBP2u1z9fW-YMck_FAzw5CYumTXT
"""

print("hello")